DROP TABLE IF EXISTS AUTHORS CASCADE;
CREATE TABLE AUTHORS
(
    ID        BIGINT PRIMARY KEY,
    FULL_NAME VARCHAR(255)
);

DROP TABLE IF EXISTS GENRES CASCADE;
CREATE TABLE GENRES
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

DROP SEQUENCE IF EXISTS BOOKS_SQ CASCADE;
CREATE SEQUENCE BOOKS_SQ START 3;

DROP TABLE IF EXISTS BOOKS CASCADE;
CREATE TABLE BOOKS
(
    ID       BIGINT DEFAULT nextval('BOOKS_SQ') PRIMARY KEY,
    NAME     VARCHAR(255),
    GENRE_ID BIGINT,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID)
);

DROP TABLE IF EXISTS BOOK_AUTHORS CASCADE;
CREATE TABLE BOOK_AUTHORS
(
    BOOK_ID   BIGINT,
    AUTHOR_ID BIGINT,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID),
    UNIQUE (BOOK_ID, AUTHOR_ID)
);

DROP SEQUENCE IF EXISTS BOOK_COMMENTS_SQ CASCADE;
CREATE SEQUENCE BOOK_COMMENTS_SQ START 2;

DROP TABLE IF EXISTS BOOK_COMMENTS CASCADE;
CREATE TABLE BOOK_COMMENTS
(
    ID       BIGINT DEFAULT nextval('BOOK_COMMENTS_SQ') PRIMARY KEY,
    TEXT     VARCHAR(255),
    CREATED_ON TIMESTAMP WITH TIME ZONE,
    BOOK_ID  BIGINT,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE
);