spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:h2:mem:batchdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    mongodb:
      database: springbatchdb
#      host: localhost
#      port: 27017

#mongock:
#  runner-type: InitializingBean
#  change-logs-scan-package:
#    - ru.otus.springbatch.chandgelogs