spring:
  datasource:
    url: jdbc:h2:mem:libdb
    initialization-mode: always
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none
    #    show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
  #        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
