spring:
  datasource:
    url: ${DB_URL}
    initialization-mode: always
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
