spring:
  datasource:
    url: ${POSTGRES_URL}/${POSTGRES_DB}
    initialization-mode: always
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${POSTGRES_DRIVER}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
