spring:
  data:
    mongodb:
      database: lib

mongock:
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.springdatamongodb.changelogs