version: '3'
services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    container_name: app
    ports:
      - 8080:8080
    env_file:
      - dev.env
    environment:
      - WAIT_FOR=postgres:5432
    networks:
      - nw
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - dev.env
    networks:
      - nw
networks:
  nw:
